apiVersion: v1
kind: ConfigMap
metadata:
  namespace: secondary
  name: coredns-proxy-config
data:
  Corefile: |
    .:53 {
      forward . 10.106.183.105:53
      debug
      log
    }
    .:3053 {
      forward . 172.17.0.10:53
      debug
      log
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: secondary
  name: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  replicas: 1
  template:
    metadata:
      namespace: secondary
      labels:
        app: proxy
    spec:
      containers:
        - name: proxy
          image:  835841513702.dkr.ecr.us-west-2.amazonaws.com/pathfinder/lab/coredns:redis
          args: ["--conf=/etc/config/Corefile"]
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 53
              protocol: TCP
              name: dns-tcp
            - containerPort: 53
              protocol: UDP
              name: dns-udp
          volumeMounts:
            - name: coredns-config
              mountPath: /etc/config
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "1Gi"
              cpu: "1"
      volumes:
        - name: coredns-config
          configMap:
            name: coredns-proxy-config
---
apiVersion: v1
kind: Service
metadata:
  namespace: secondary
  name: proxy
  labels:
    app: proxy
spec:
  ports:
    - port: 53
      name: dns-tcp
      targetPort: dns-tcp
      protocol: TCP
    - port: 53
      name: dns-udp
      targetPort: dns-udp
      protocol: UDP
  selector:
    app: proxy
  clusterIP: 10.106.183.110